### PR TITLE
Bump to Polkadot 1.1.0

### LINKED ISSUE #17: Update to Polkadot version 1.1.0
Related to [tasks/#306](https://github.com/pendulum-chain/tasks/issues/306)

To perform the upgrade of Pendulum to Polkadot release `1.1.0` we need to update this repository to [polkadot-sdk release v1.1.0](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.1.0).

If benchmarking of this pallet can be [done](https://github.com/pendulum-chain/pendulum?tab=readme-ov-file#how-to-benchmark-runtime-pallets) properly on Pendulum, we can also remove the `node` and `runtime` of this repository ([discussion](https://github.com/pendulum-chain/oracle-pallet/pull/18#issuecomment-2139354068)).

### PR DESCRIPTION
**Pull request by gianfra-t**
Closes #17.
This branch `polkadot-v1.1.0` should be kept after merging with `master`.

Aside from the changes required by the upgrade, we removed the `runtime` and `node` parts. The intention is to perform the benchmarks directly on the Pendulum repository and use those weights generated, like it is done with our other custom pallets ([example](https://github.com/pendulum-chain/pendulum/blob/178-add-benchmarks-for-custom-pallets-per-runtime/runtime/pendulum/src/lib.rs#L1278))

<s>Before Merging this:  we first need to merge [this](https://github.com/pendulum-chain/pendulum/pull/453), then made the code modifications to [upgrade](https://github.com/pendulum-chain/pendulum/issues/481#issue-2324002036) to `1.1.0` on the runtimes, add this pallet in the benchmark list macro and perform the benchmark.</s>

Once [this](https://github.com/pendulum-chain/oracle-pallet/pull/26) small fix is merged into this branch, we can finally close the PR, since weights were [generated](https://github.com/pendulum-chain/pendulum/pull/489/commits/44bbd06cd9314d805296f743cc2c82e09012becb) on pendulum.

### CODE REVIEW

**Comment by gianfra-t** [comment]
@pendulum-chain/devs I've selected channel `nightly-2023-10-26` for this new version rather arbitrarily, do we have any methodology for selecting the channel?

**Comment by ebma** [comment]
> I've selected channel nightly-2023-10-26 for this new version rather arbitrarily, do we have any methodology for selecting the channel?

I think it's best to always update to the latest nightly channel that still works _when_ we touch that rust-toolchain file. Some nightly versions will result in new compiler errors for some reason but when it comes to versions the later the better I guess. 


> Before Merging this: we first need to merge https://github.com/pendulum-chain/pendulum/pull/453,

Why do we need to wait for that?

**Comment by gianfra-t** [comment]
> it's best to always update to the latest nightly channel that still works 

Good idea, I will try to find a newer one. I took this one from a sibling chain's code using the same version.

> Why do we need to wait for that?

Not really need to, but this fixes compiling the runtime with `runtime-benchmarks` feature. In any case, we still need to perform the update to `1.1.0` on the runtime before we can benchmark this new version of the pallet. I guess we can also merge [that](https://github.com/pendulum-chain/pendulum/pull/453) branch into the `1.1.0` if it hasn't been merged with main so we can compile and do the benchmark. WDYT?

**Comment by TorstenStueber** [comment]
I am not an expert on toolchains, but with [this PR](https://github.com/pendulum-chain/pendulum/issues/444) didn't we decide that we want to use stable now instead of nightly?

**Review by TorstenStueber — APPROVED** [review]

**Comment by gianfra-t** [comment]
I could try with stable also, but we are not using any of the tools that stopped working with nightly right?

**Comment by ebma** [comment]
> but with https://github.com/pendulum-chain/pendulum/issues/444 didn't we decide that we want to use stable now instead of nightly?

Good point. Let's try to define the same version as we are [using on Pendulum ](https://github.com/pendulum-chain/pendulum/blob/991c7694084c22ee61716723d001163e746a1725/rust-toolchain.toml) at the moment. I think generally it wouldn't matter what toolchain version we are defining here as long as all the crates then also compile on the toolchain used in Pendulum. Which we can only 100% guarantee by using the same toolchain here.

**Comment by gianfra-t** [comment]
I pushed the use of stable `1.77.0` and also fixes for `cargo test`.

**Review by ebma — APPROVED** [review]
Nice 👍

**Review by TorstenStueber — APPROVED** [review]

**Comment by gianfra-t** [comment]
I think we can merge this PR.

**Pull request merged**
