### PR TITLE
Polkadot v0.9.42

### PR DESCRIPTION
**Pull request by gianfra-t**
We want master to track always the latest branch used.

### CODE REVIEW

**Comment by TorstenStueber** [comment]
The whole code in the `/node` folder does not actually matter, correct? Maybe it's best to just remove it in order to save maintenance overhead and avoid confusion.

**Review by TorstenStueber — APPROVED** [review]

**Comment by ebma** [comment]
> The whole code in the /node and /runtime folders does not actually matter, correct? 

True, removing it is a great idea. Let's do that. Can you please create the follow-up ticket for this @gianfra-t?

**Review by ebma — APPROVED** [review]

**Comment by gianfra-t** [comment]
We can remove it as part of [this](https://github.com/pendulum-chain/oracle-pallet/issues/17), or at least before it since it doesn't make sense to update code that is not used. Are we sure we don't use it for benchmarking the pallet?

**Comment by TorstenStueber** [comment]
I am fine with removing it in the PR for the upgrade to 1.1.0.

But important part about the benchmarking: please check whether the code would still be required for benchmarking. Maybe it is possible to do it via the Pendulum repository instead...

**Comment by gianfra-t** [comment]
I believe we should do it in the pendulum repo, like we did with [this](https://github.com/pendulum-chain/pendulum/pull/453) change for the Spacewalk pallets.

**Pull request merged**
